# Generated by Django 5.1.6 on 2025-02-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
