# Generated by Django 5.1.4 on 2025-01-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('Sales Manager', 'Sales Manager'), ('Marketing Specialist', 'Marketing Specialist'), ('Real Estate Agent', 'Real Estate Agent'), ('Campaign Manager', 'Campaign Manager'), ('Admin', 'Admin')], max_length=50, verbose_name='Role')),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Administration', 'Administration')], max_length=50, verbose_name='Department')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
