# Generated by Django 5.1.6 on 2025-02-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Offer Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('offer_type', models.CharField(choices=[('Discount', 'Discount'), ('Cashback', 'Cashback'), ('Exclusive', 'Exclusive Deal')], max_length=20, verbose_name='Offer Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Value')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Purchase Amount')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Upcoming', 'Upcoming')], default='Active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Assigned Employee')),
                ('clients', models.ManyToManyField(blank=True, to='clients.client', verbose_name='Applicable Clients')),
                ('properties', models.ManyToManyField(blank=True, to='properties.property', verbose_name='Applicable Properties')),
            ],
        ),
    ]
