# Generated by Django 5.1.4 on 2025-01-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_request_details_client_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
