# Generated by Django 5.1.6 on 2025-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Standalone Villa', 'Standalone Villa'), ('Twin Villa', 'Twin Villa'), ('Town Villa', 'Town Villa'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Apartment', 'Apartment'), ('Shop', 'Shop'), ('Office', 'Office'), ('Clinic', 'Clinic')], max_length=50, verbose_name='Property Type')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('developer', models.CharField(max_length=255, verbose_name='Developer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Property Description')),
                ('area', models.FloatField(verbose_name='Area (sqm)')),
                ('outdoor_area', models.FloatField(blank=True, null=True, verbose_name='Outdoor Area (sqm)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Installment', 'Installment')], max_length=20, verbose_name='Payment Method')),
                ('delivery_method', models.TextField(verbose_name='Delivery Method')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('payment_percentage_for_delivery', models.FloatField(verbose_name='Payment Percentage for Delivery (%)')),
                ('maintenance_value_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=20, verbose_name='Maintenance Value Type')),
                ('maintenance_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Maintenance Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
