# Generated by Django 5.1.6 on 2025-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google Ads'), ('TikTok', 'TikTok Ads'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=50, verbose_name='Advertising Platform')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed')], max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('campaign_url', models.URLField(blank=True, null=True, verbose_name='Campaign URL')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'constraints': [models.UniqueConstraint(fields=('name', 'platform'), name='unique_campaign_per_platform')],
            },
        ),
    ]
