# Generated by Django 5.1.6 on 2025-02-09 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_created_at_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Deduction Type')),
            ],
            options={
                'verbose_name': 'Deduction Type',
                'verbose_name_plural': 'Deduction Types',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='IncentiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Incentive Type')),
            ],
            options={
                'verbose_name': 'Incentive Type',
                'verbose_name_plural': 'Incentive Types',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Job Title')),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus Amount')),
                ('reason', models.TextField(verbose_name='Reason for Bonus')),
                ('date_given', models.DateField(default=django.utils.timezone.now, verbose_name='Bonus Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deduction Amount')),
                ('reason', models.TextField(verbose_name='Reason for Deduction')),
                ('date_given', models.DateField(default=django.utils.timezone.now, verbose_name='Deduction Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Sales')),
                ('commission_earned', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission Earned')),
                ('date_calculated', models.DateField(default=django.utils.timezone.now, verbose_name='Commission Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Sales Commission',
                'verbose_name_plural': 'Sales Commissions',
                'ordering': ['-date_calculated'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Salary')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission Rate (%)')),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fixed Commission per Million')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Deduction (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
                'constraints': [models.UniqueConstraint(fields=('employee',), name='unique_salary_per_employee')],
            },
        ),
    ]
